[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=63.0.0", "wheel"]

[tool.black]
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/tmp
'''
include = '\.pyi?$'
target-version = ['py37', 'py38', 'py39', 'py310']

[tool.isort]
combine_as_imports = true
indent = '    '
known_future_library = ['__future__', 'datahub.utilities._markupsafe_compat', 'datahub.sql_parsing._sqlglot_patch']
profile = 'black'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
skip_glob = 'src/datahub/metadata'

[tool.pyright]
extraPaths = ['tests']

[tool.vulture]
exclude = ["src/datahub/metadata/"]
ignore_decorators = ["@click.*", "@validator", "@root_validator", "@pydantic.validator", "@pydantic.root_validator", "@pytest.fixture"]
ignore_names = ["*Source", "*Sink", "*Report"]
paths = ["src"]
sort_by_size = true

[tool.ruff]
# Same as Black.
line-length = 88
# Exclude directories matching these patterns.
exclude = [
    ".git",
    "src/datahub/metadata",
    "venv",
    ".tox",
    "__pycache__",
]

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore = [
    # Ignore line length violations (handled by Black)
    "E501",
    # Ignore whitespace before ':' (matches Black)
    "E203",
    # Allow usages of functools.lru_cache
    "B019",
    # Allow function call in argument defaults
    "B008",
    # TODO: Enable these later as mentioned in original config
    "B006",  # Mutable args
    "B007",  # Unused loop control variable
    # Below these were added while migrating flake8 to ruff to avoid making lot of changes
    "B904", 
    "B017",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]