version: '3.8'
services:   
  kibana:
    image: kibana:7.9.3
    env_file: kibana/env/docker.env
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    #depends_on:
      #- elasticsearch      

networks:
  default:
    name: datahub_network

volumes:
  esdata:
  zkdata:
