apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-mae-consumer-deployment
  labels:
    app: datahub-mae-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-mae-consumer
  template:
    metadata:
      labels:
        app: datahub-mae-consumer
    spec:
      hostAliases:
        - ip: "192.168.0.104" #TODO: This is the IP Address of the host machine where rest of the services are running. Need to update it temporarily
          hostnames:
            - "mysql"
            - "broker"
            - "elasticsearch"
            - "neo4j"
      containers:
        - name: datahub-mae-consumer
          image: keremsahin/datahub-mae-consumer:latest
          command: ["/bin/bash", "-c" ,"./mae-consumer-job/bin/mae-consumer-job"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: kafka.bootstrap.server
            - name: KAFKA_SCHEMAREGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: kafka.schemaregistry.url
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: elasticsearch.host
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: elasticsearch.port
            - name: NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: neo4j.uri
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: datahub-secret
                  key: neo4j.username
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datahub-secret
                  key: neo4j.password
