ingestion:
- any: [
  'metadata-ingestion/**/*'
]

devops:
- any: [
  'docker/**/*', 
  '.github/**/*'
]

product:
- any: [
  'datahub-web-react/**/*', 
  'datahub-frontend/**/*', 
  'datahub-graphql-core/**/*'
]

docs:
- any: [
  'docs/**/*'
]