kind: pipeline
name: default

concurrency:
  limit: 1

anchors:
  docker_build_config: &docker_build_config
    image: plugins/ecr
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USER:
        from_secret: ARTIFACTORY_USER
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    settings:
      create_repository: true
      region: eu-west-1
      assume_role: arn:aws:iam::131063299351:role/automation-drone
      repository_policy: .ecr-repository-policy.json
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_BRANCH}
      dockerfile: ./Dockerfile
      build_args_from_env:
        - ARTIFACTORY_PASSWORD
        - ARTIFACTORY_USER
        - GITHUB_TOKEN

steps:
  - name: gradle_build_frontend
    image: gradle:jdk11
    commands:
      - ./gradlew :datahub-frontend:build :datahub-web-react:build --parallel 

  - name: docker_build_frontend
    <<: *docker_build_config
    settings:
      dockerfile: ./docker/datahub-frontend/Dockerfile
      repo: datahub-frontend 
      custom_labels:
      - "org.fundingcircle.image.manager=data-platform@fundingcircle.com"
      cache_from:
      - 131063299351.dkr.ecr.eu-west-1.amazonaws.com/datahub-frontend:${DRONE_BRANCH//\//-}
    depends_on:
      - gradle_build_frontend
