source:
  type: vertica
  config:
  #   # # Coordinates
 

    #Coordinates
    host_port: 172.16.121.12:5433
    database: Vmart

    # #Credentials
    username: "dbadmin"
    password: "simplify3xdb"

    # host_port: 140.236.88.151:5433
    # database: PartPub80DB
    # # #Credentials
    # username: "datahub_user"
    # password: "datahub_22"

    # host_port: 172.16.121.14:5433
    # database: vmart
    # # #Credentials
    # username: "dbadmin"
    # password: "abc123"
 


    include_tables: true
    include_views: true
    include_projections: true
    include_models: false
    include_oauth: false
    include_view_lineage: true
    include_projection_lineage: true
   
    # stateful_ingestion:
    #   enabled: true
    #   remove_stale_metadata: true
      
    profiling: 
      enabled: false
      # limit: null
      # offset: null
      # report_dropped_profiles: true
      # turn_off_expensive_profiling_metrics: true
      # profile_table_level_only: false
      # include_field_null_count: true
      # include_field_min_value: true
      # include_field_max_value: true
      # include_field_mean_value: true
      # include_field_median_value: true
      # include_field_stddev_value: true
      # include_field_quantiles: true
      # include_field_distinct_value_frequencies: tru
      # include_field_histogram: true
      # include_field_sample_values: true
      # max_number_of_fields_to_profile: 20
      # profile_if_updated_since_days: 1
      # profile_table_size_limit: 1
      # profile_table_row_limit: 50000
      max_workers: 90
      # query_combiner_enabled: true
      # catch_exceptions: true
      # partition_profiling_enabled: true
      # bigquery_temp_table_schema: null
      # partition_datetime: null

# source:
#   type: file
#   config:
#     # Coordinates
#     filename: demo_data.json

sink:
  # sink configs
  # type: "datahub-kafka"
  # config:
  #   connection:
  #     bootstrap: "localhost:9092"
  type: 'datahub-rest'

  config:
    server: 'http://localhost:8080' 
    max_threads: 90

pipeline_name: 'new1'

# transformers:
#   - type: "simple_add_dataset_ownership"
#     config:
#       owner_urns:
#         - "urn:li:corpuser:dbadmin"
#       ownership_type: "PRODUCER"
transformers:
      # - type: "simple_add_dataset_domain"
      #   config:
      #     semantics: OVERWRITE
      #     domains:
      #       - urn:li:domain:vertica
      # - type: "simple_add_dataset_ownership"
      #   config:
      #     owner_urns:
      #       - "urn:li:corpuser:dbadmin"
      #     ownership_type: "PRODUCER"
      # - type: simple_add_dataset_tags
      #   config:
      #     tag_urns:
      #       - "urn:li:tag:test"
      