apiVersion: skaffold/v2beta17
kind: Config
profiles:
  - name: local
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}"
        gitCommit:
          ignoreChanges: true
      artifacts:
      - image: datahub-gms
        custom:
          buildCommand: ./gradlew :gms:war:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-gms/Dockerfile
      - image: datahub-frontend
        custom:
          buildCommand: ./gradlew :datahub-frontend:dist -PenableEmber=false -x :datahub-web-react:yarnTest
          dependencies:
            dockerfile:
              path: ./docker/datahub-frontend/Dockerfile
      - image: datahub-mae-consumer
        custom:
          buildCommand: ./gradlew :metadata-jobs:mae-consumer-job:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-mae-consumer/Dockerfile
      - image: datahub-mce-consumer
        custom:
          buildCommand: ./gradlew :metadata-jobs:mce-consumer-job:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-mce-consumer/Dockerfile
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        paths: [./kubernetes/base]
  - name: dev-tokyo
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
      artifacts:
      - image: datahub-gms
        custom:
          buildCommand: ./gradlew :gms:war:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-gms/Dockerfile
      - image: datahub-frontend
        custom:
          buildCommand: ./gradlew :datahub-frontend:dist -PenableEmber=false -x :datahub-web-react:yarnTest
          dependencies:
            dockerfile:
              path: ./docker/datahub-frontend/Dockerfile
      - image: datahub-mae-consumer
        custom:
          buildCommand: ./gradlew :metadata-jobs:mae-consumer-job:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-mae-consumer/Dockerfile
      - image: datahub-mce-consumer
        custom:
          buildCommand: ./gradlew :metadata-jobs:mce-consumer-job:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-mce-consumer/Dockerfile
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        paths: [./kubernetes/dev/tokyo]
  - name: prd-tokyo
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
      artifacts:
      - image: datahub-gms
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-gms
      - image: datahub-frontend
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-frontend
      - image: datahub-mae-consumer
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-mae-consumer
      - image: datahub-mce-consumer
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-mce-consumer
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        paths: [./kubernetes/prd/tokyo]
