apiVersion: skaffold/v1beta16
kind: Config
profiles:
  - name: local
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}"
      artifacts:
        - image: datahub-gms
          custom:
            buildCommand: ./gradlew build
          context: ./docker/datahub-gms
        - image: datahub-frontend-react
          custom:
            buildCommand: ./gradlew build
          context: ./docker/datahub-frontend
        - image: datahub-mae-consumer
          custom:
            buildCommand: ./gradlew build
          context: ./docker/datahub-mae-consumer
        - image: datahub-mce-consumer
          custom:
            buildCommand: ./gradlew build
          context: ./docker/datahub-mce-consumer
    deploy:
      kustomize:
        path: ./kubernetes/base
  - name: dev-tokyo
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
      artifacts:
      - image: datahub-gms
        custom:
          buildCommand: ./gradlew :gms:war:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-gms/Dockerfile
      - image: datahub-frontend
        custom:
          buildCommand: ./gradlew :datahub-frontend:dist -PenableEmber=false
          dependencies:
            dockerfile:
              path: ./docker/datahub-frontend/Dockerfile
      - image: datahub-mae-consumer
        custom:
          buildCommand: ./gradlew :metadata-jobs:mae-consumer-job:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-mae-consumer/Dockerfile
      - image: datahub-mce-consumer
        custom:
          buildCommand: ./gradlew :metadata-jobs:mce-consumer-job:build
          dependencies:
            dockerfile:
              path: ./docker/datahub-mce-consumer/Dockerfile
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        path: ./kubernetes/dev/tokyo
  - name: prd-tokyo
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
      artifacts:
      - image: datahub-gms
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-gms
      - image: datahub-frontend
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-frontend
      - image: datahub-mae-consumer
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-mae-consumer
      - image: datahub-mce-consumer
        custom:
          buildCommand: ./gradlew build
        context: ./docker/datahub-mce-consumer
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        path: ./kubernetes/prd/tokyo
