apiVersion: skaffold/v2beta17
kind: Config
profiles:
  - name: local
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
          ignoreChanges: true
      artifacts:
      - image: datahub-gms
        docker:
          dockerfile: ./docker/datahub-gms/Dockerfile
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        paths: [./kubernetes/base]
  - name: dev-tokyo
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
      artifacts:
      - image: datahub-gms
        docker:
          dockerfile: ./docker/datahub-gms/Dockerfile
      - image: datahub-frontend
        docker:
          dockerfile: ./docker/datahub-frontend/Dockerfile
      - image: datahub-mae-consumer
        docker:
          dockerfile: ./docker/datahub-mae-consumer/Dockerfile
      - image: datahub-mce-consumer
        docker:
          dockerfile: ./docker/datahub-mce-consumer/Dockerfile
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        paths: [./kubernetes/dev/tokyo]
  - name: prd-tokyo
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
      artifacts:
      - image: datahub-gms
        docker:
          dockerfile: ./docker/datahub-gms/Dockerfile
      - image: datahub-frontend
        docker:
          dockerfile: ./docker/datahub-frontend/Dockerfile
      - image: datahub-mae-consumer
        docker:
          dockerfile: ./docker/datahub-mae-consumer/Dockerfile
      - image: datahub-mce-consumer
        docker:
          dockerfile: ./docker/datahub-mce-consumer/Dockerfile
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        paths: [./kubernetes/prd/tokyo]
