version: 2.1

orbs:
  gradle: smartnews/gradle@1

orb_dockers:
  gradle: &orb_docker_gradle 165463520094.dkr.ecr.ap-northeast-1.amazonaws.com/circleci-orbs/gradle:8.0-1

workflow_filters:
  branch-filter: &branch-filter
    filters:
      branches:
        ignore:
          - master
  master-filter: &master-filter
    filters:
      branches:
        only: master

workflows:
  deliver-dev:
    jobs:
      - gradle/deliver:
          <<: *branch-filter
          name: deliver/dev/gms
          docker: *orb_docker_gradle
          env: dev
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: gms
      - gradle/deliver:
          <<: *branch-filter
          name: deliver/dev/frontend
          docker: *orb_docker_gradle
          env: dev
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: frontend
      - gradle/deliver:
          <<: *branch-filter
          name: deliver/dev/mae-consumer
          docker: *orb_docker_gradle
          env: dev
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: mae-consumer
      - gradle/deliver:
          <<: *branch-filter
          name: deliver/dev/mce-consumer
          docker: *orb_docker_gradle
          env: dev
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: mce-consumer
  deliver-prd:
    jobs:
      - gradle/deliver:
          <<: *master-filter
          name: deliver/dev/gms
          docker: *orb_docker_gradle
          env: prd
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: gms
      - gradle/deliver:
          <<: *master-filter
          name: deliver/dev/frontend
          docker: *orb_docker_gradle
          env: prd
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: frontend
      - gradle/deliver:
          <<: *master-filter
          name: deliver/dev/mae-consumer
          docker: *orb_docker_gradle
          env: prd
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: mae-consumer
      - gradle/deliver:
          <<: *master-filter
          name: deliver/dev/mce-consumer
          docker: *orb_docker_gradle
          env: prd
          region: tokyo
          cluster: spaas_sn
          system: data-catalogue
          target: mce-consumer
parameters:
  workflow_main:
    type: boolean
    default: true
  workflow_terraform:
    type: boolean
    default: false
  env:
    type: string
    default: ""
  region:
    type: string
    default: ""
  system:
    type: string
    default: ""
  path:
    type: string
    default: ""
