apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: datahub-gms
  name: datahub-gms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datahub-gms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/datahub_network: "true"
        io.kompose.service: datahub-gms
    spec:
      containers:
        - env:
            - name: DATAHUB_MAE_CONSUMER_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATAHUB_MAE_CONSUMER_PORT
                  name: datahub-gms-env
            - name: KIBANA_PORT
              valueFrom:
                configMapKeyRef:
                  key: KIBANA_PORT
                  name: datahub-gms-env
            - name: DATAHUB_MCE_CONSUMER_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATAHUB_MCE_CONSUMER_PORT
                  name: datahub-gms-env               
            - name: DATAHUB_FRONTEND_REACT_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATAHUB_FRONTEND_REACT_PORT
                  name: datahub-gms-env               
            - name: DATAHUB_GMS_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATAHUB_GMS_PORT
                  name: datahub-gms-env               
            - name: KAFKA_TOPICS_UI_PORT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPICS_UI_PORT
                  name: datahub-gms-env               
            - name: SCHEMA_REGISTRY_UI_PORT
              valueFrom:
                configMapKeyRef:
                  key: SCHEMA_REGISTRY_UI_PORT
                  name: datahub-gms-env               
            - name: KUBERNETES_PORT
              valueFrom:
                configMapKeyRef:
                  key: KUBERNETES_PORT
                  name: datahub-gms-env               
            - name: KAFKA_REST_PROXY_PORT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_REST_PROXY_PORT
                  name: datahub-gms-env               
            - name: SCHEMA_REGISTRY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: SCHEMA_REGISTRY_SERVICE_PORT
                  name: datahub-gms-env               
            - name: BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  key: BROKER_PORT
                  name: datahub-gms-env               
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  key: ELASTICSEARCH_PORT
                  name: datahub-gms-env               
          image: datahub-gms
          name: datahub-gms
          ports:
            - containerPort: 8080
          resources: {}
      hostname: datahub-gms
      restartPolicy: Always
status: {}
