name: check quickstart
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  test-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/setup-python@v2
        with:
          python-version: "3.9.9"
    - name: Install acryl-datahub
      run: |
        pip install --upgrade acryl-datahub
        datahub version
        datahub docker quickstart
         