name: check quickstart
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  test-quickstart:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9.9"
    - name: Install acryl-datahub
      run: |
        pip install --upgrade acryl-datahub
        datahub version
        python  -c "import platform; print(platform.platform())"
    - name: Run quickstart
      run: |
        datahub docker quickstart