name: documentation

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  # release:
  #   types: [published, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Start Deployment
        if: github.event_name == 'pull_request' && github.repository == 'datahub-project/datahub'
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          env: docs-preview

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Build Docs
        run: |
          ./gradlew --info docs-website:build
      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'datahub-project/datahub'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-website/build
          cname: datahubproject.io

      - name: Deploy Preview
        uses: amondnet/vercel-action@v20
        if: github.event_name == 'pull_request' && github.repository == 'datahub-project/datahub'
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-comment: false
          working-directory: ./docs-website/build

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.vercel-action.outputs.preview-url }}
