# This is a basic workflow to help you get started with Actions

name: spark-smoke

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Gradle build
        run: ./gradlew build -x check -x docs-website:build -x signArchives
      - name: build java test library
        working-directory: smoke-test/spark-smoke-test/test-spark-lineage
        run: ./gradlew build
      - name: Smoke test
        run: ./smoke-test/spark-smoke-test/smoke.sh
          
